name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can use a Linux runner for simplicity

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setup Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v2
        with:
          azure-cliversion: latest

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App (static site deployment)
      - name: Deploy to Azure Web App
        run: |
          # Deploy your files to the Azure Web App
          az webapp deploy --resource-group <your-resource-group> --name <your-webapp-name> --src-path . --type zip
