name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install Azure CLI manually
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App (static site deployment)
      - name: Deploy to Azure Web App
        run: |
          # Deploy your files to the Azure Web App
          az webapp deploy --resource-group <your-resource-group> --name <your-webapp-name> --src-path . --type zip
